# Generated by Django 2.1.1 on 2021-04-16 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_URL', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MangaSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manga_URL', models.URLField(default=None, unique=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('latest_chapter', models.CharField(default=None, max_length=100)),
                ('paused', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mangachapters',
            name='manga_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_series', to='updates.MangaSeries'),
        ),
        migrations.AddField(
            model_name='mangachapters',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
